const express = require('express');
const nodemailer = require('nodemailer');

const router = express.Router();

// Configure the nodemailer transporter using env variables
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.SMTP_PORT || '587', 10),
  secure: false, // true for 465, false for other ports
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

router.post('/', async (req, res) => {
  try {
    const { name, email, mobile, company, message, selected_modules, scope } = req.body;

    if (!name || !email) {
      return res.status(400).json({ error: 'Name and email are required' });
    }

    const adminEmail = process.env.ADMIN_EMAIL;
    if (!adminEmail) {
      return res.status(500).json({ error: 'Server misconfiguration: missing ADMIN_EMAIL' });
    }

    // Format the selected modules safely
    const modulesList = (selected_modules && selected_modules.length > 0)
      ? `<ul>${selected_modules.map(mod => `<li>${mod}</li>`).join('')}</ul>`
      : '<p><em>No specific modules selected.</em></p>';

    const htmlBody = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; padding: 20px; border: 1px solid #eee; border-radius: 5px;">
        <h2 style="color: #333;">New Sales Inquiry</h2>
        <p>You have received a new "Talk to Sales" lead from the Perfy portal.</p>
        
        <h3 style="border-bottom: 1px solid #ddd; padding-bottom: 5px; color: #555;">Contact Details</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <tr><td style="padding: 8px 0; font-weight: bold; width: 120px;">Name:</td><td>${name}</td></tr>
          <tr><td style="padding: 8px 0; font-weight: bold;">Email:</td><td><a href="mailto:${email}">${email}</a></td></tr>
          <tr><td style="padding: 8px 0; font-weight: bold;">Mobile:</td><td>${mobile}</td></tr>
          <tr><td style="padding: 8px 0; font-weight: bold;">Company:</td><td>${company || '<em>Not provided</em>'}</td></tr>
        </table>

        <h3 style="border-bottom: 1px solid #ddd; padding-bottom: 5px; color: #555; margin-top: 25px;">Plan & Requirements</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <tr><td style="padding: 8px 0; font-weight: bold; width: 120px;">Scope:</td><td><span style="background: #eee; padding: 3px 8px; border-radius: 12px; font-size: 12px; text-transform: capitalize;">${scope || 'Individual'}</span></td></tr>
          <tr>
            <td style="padding: 8px 0; font-weight: bold; vertical-align: top;">Modules:</td>
            <td>${modulesList}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; font-weight: bold; vertical-align: top;">Message:</td>
            <td>
              <div style="background: #f9f9f9; padding: 10px; border-left: 3px solid #ccc; white-space: pre-wrap;">${message || '<em>No additional message provided.</em>'}</div>
            </td>
          </tr>
        </table>
        
        <p style="margin-top: 30px; font-size: 12px; color: #888;">This email was automatically generated by the Perfy system.</p>
      </div>
    `;

    const mailOptions = {
      from: `"${process.env.FROM_NAME || 'Perfy Team'}" <${process.env.SMTP_USER}>`,
      to: adminEmail,
      subject: `New Sales Lead: ${name} (${company || 'Individual'})`,
      html: htmlBody,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log(`Sales inquiry sent: ${info.messageId}`);
    
    return res.status(200).json({ success: true, message: 'Sales inquiry sent successfully' });
  } catch (error) {
    console.error('Error sending sales email:', error);
    return res.status(500).json({ error: 'Failed to send sales inquiry', details: error.message });
  }
});

module.exports = router;
